### ISSUE TITLE
Integration with Google Calendar?

### ISSUE THREAD

**Issue by naveenjafer** [fossasia/timeline.api.fossasia.net#6]
Why not integrate this with the google calendar API to make it more useful and accessible. I would be more than willing to work on it if we could have a short brainstorming session with someone who has contributed heavily to the project and would know more about the difficulties that we might run into.
@zyzo @andibraeu

**Comment by zyzo** [comment]
Hi @naveenjafer, could you be more explicit on what kind of integration you're having in mind ? 

For your information, this timeline is just a front-end library, which uses the Calendar API developped in common.api.fossasia.net. More about the API [here](https://github.com/fossasia/common.api.fossasia.net/tree/master/ics-collector).

**Comment by naveenjafer** [comment]
Hi @zyzo Really sorry about that! I had not mentioned that clearly. What I intend is to add a "add to calendar" option just beside the event in the timeline(not the underlying API) that could add the event to google calendar. https://developers.google.com/google-apps/calendar/v3/reference/events/insert#examples The idea is to make use of data that is already returned by the common.api.fossasia.net and process it to enable adding a calendar event. The one problem that I would foresee was how to avoid duplicate events from being added(basically a way for the user to know if he/she has already added the event to their calendar).

**Comment by zyzo** [comment]
That's a good idea ! Please go ahead and implement it, let's not worry about the minor duplication problem (for now) :).

**Comment by naveenjafer** [comment]
Great! I will get started on it as soon as possible! Will mark you here if I face any troubles :)

**Comment by naveenjafer** [comment]
@zyzo  Hi, there is one issue with the implementation though. The API requires us to give the URL domain of the page to validate authentications. Since the users will all be hosting it in their own servers, we might have to redirect to some page hosted by us on Github to handle all these requests. For now I am going and implementing it with this small extra overhead of completing required action in a new tab that the user will be redirected to.

**Comment by naveenjafer** [comment]
@zyzo got a heroku app to handle the requests. Will complete it in a couple of days and send you a request. :)

**Comment by zyzo** [comment]
Great ! Please don't hesitate to ask if there is any trouble.

**Comment by naveenjafer** [comment]
@zyzo One small clarification. The timezones that these events are created for. Which timezones are these times representative of? Is it the local time of the respective country or IST?

**Comment by zyzo** [comment]
@naveenjafer These are all represented in standard timezone (UTC or GMT+0).

**Comment by naveenjafer** [comment]
@zyzo  It's done :) It's a bit rusty as of now, the way the redirects are handled, but should work for now.
